FORMAT: 1A
HOST: http://api.superdesk.org/v1/

# Superdesk Content API

The Superdesk Content Delivery API is a public API. It aims to empower news
organizations using Superdesk to open up their content to a broad community of
innovative developers and encourage the development of a diversity of news
applications to engage readers wherever they are.

# Current Version

We are currently developing the __Superdesk Content API v1__ version, the release
date is yet to be announced.

When working with the __Superdesk Content API__, you must explicitly request the
version of the API you want to use via URL, as in the following request:

```
https://api.superdesk.org/v1/items
```

# Content Model

Content in Superdesk is organized following the __News Architecture__ schema defined as
part of the [NewsML-G2](https://iptc.org/standards/newsml-g2/) standard for exchanging
news and news management.

The Superdesk Content API delivers __news items__ and __packages__. A __News Item__
represents individual general news where the content can be textual, photos, graphics,
audio and video. A __Package Item__ is a structured bundle of __news items__.

...

# Response Format

All API access is over HTTPS, and accessed through yourdomain.com/api/v1/. All
news content is delivered as JSON data. Images, audio clips, videos and other media
assets are delivered as files.

...

# HTTP Verbs

| Action    | Verb      | Description                                        |
| --------- | :-------: | -------------------------------------------------: |
| Create    | POST      | Used for creating resources                        |
| Create    | PUT       | Used for replacing resources or collections        |
| Replace   | PUT       |                                                    |
| Read      | GET, HEAD | Used for retrieving resources                      |
| Update    | PATCH     | Used for updating resources with partial JSON data |
| Delete    | DELETE    | Used for deleting resources                        |

# Status Codes

Whenever something goes wrong with an API request, the server produces an error.
The error message contains an appropriate HTTP status code in the header and a
JSON response in the body.

| HTTP Status Code    | Error Code         | Description                                                  |
| ------------------- | :----------------: | -----------------------------------------------------------: |
| 400                 | BadRequest         | The request is malformed or a required parameter is missing. |
| 401                 | Unauthorized       | The authorization token is not valid.                        |
| 403                 | Forbidden          |                                                              |
| 404                 | NotFound           | The requested resource/endpoint can not be found.            |
| 412                 | PreconditionFailed |                                                              |
| 500                 | InternalError      | Something has gone wrong on our end.                         |

# Authentication

TODO

# SDK Libraries

SDKs are simply wrappers around the RESTful API to provide an added level of convenience
for developers. If you are planning to write an application that handles Superdesk content,
the SDK is the way to go to interact with the Content API.

## PHP

https://github.com/superdesk/contentapi-sdk-php

```
git clone git@github.com:superdesk/contentapi-sdk-php.git
``` 

If you can't find an SDK for your language of choice, you can help us building it by
yourself and contributing it to the Superdesk community. We are planning to work on
new SDKs and this is the space to watch in order to know about it.

# API Updates

To learn about future enhancements to the Content API and new versions of it, keep an
eye on this space. We will make sure you are properly informed on any changes made.

# Support

TODO


# Group API Resources

## Root Endpoint [/]

### Fetch all available resources [GET]

+ Response 200 (application/json)

        {
            "_links": {
                "child": [
                    {
                        "href": "publish",
                        "title": "publish"
                    },
                    {
                        "href": "assets",
                        "title": "assets"
                    },
                    {
                        "href": "items",
                        "title": "items"
                    },
                    {
                        "href": "prepopulate",
                        "title": "prepopulate"
                    },
                    {
                        "href": "packages",
                        "title": "packages"
                    }
                ]
            }
        }

# Group Content Items

In Superdesk, a News Item is a generic container for any type of news content.
Photos, text, audio, video and graphics are all represented as News Items.

## Text News Item [/items/{_id}]


### Fetch a single Text News Item [GET]

This method is used to retrieve a particular item as a NewsML-G2 News Item
document in its ninjs (News in JSON) representation. To invoke this method, you
must know the item Id of the News Item you want to retrieve.

+ Parameters
    + _id (required, string, `1`) ... Identifier of the News Item you want to retrieve.

+ Response 200 (application/json)

        {
            "_links": {
                "parent": {"href": "/", "title": "home"},
                "collection": {"href": "items", "title": "items"},
                "self": {"href": "items/tag:example.com,0000:newsml_BRE9A605", "title": "Item"}
            },
            "uri" : "http://site.com/items/tag:example.com,0000:newsml_BRE9A605",
            "type" : "text",
            "profile" : "text-html",
            "versioncreated" : "2015-01-11T12:42:00Z",
            "version": 1,
            "copyrightnotice" : "Copyright 2015 News Agency, site.com - all rights reserved.",
            "language" : "en",
            "person" : [{
                "name" : "John Doe",
                "rel" : "about",
                "scheme" : "http://site.com/scheme/",
                "code" : "0hzcydt"
            }],
            "place" : [
                {"name" : "Paris", "rel" : "mentions"},
                {"name" : "France", "rel" : "mentions", "code" : "fr"}
            ],
            "organisation" : [{
                "name" : "Organisation",
                "rel" : "mentions"
            }],
            "byline" : "John Doe",
            "located" : "Paris, France",
            "headline" : "Today's News",     
            "body_text" : "Lorem ipsum",
            "body_html" : "<p>Lorem ipsum</p>"
        }

## Picture News Item [/items/{_id}]


### Fetch a single Picture News Item [GET]

This method is used to retrieve a particular item as a NewsML-G2 News Item
document in its ninjs (News in JSON) representation. To invoke this method, you
must know the item Id of the News Item you want to retrieve.

+ Parameters
    + _id (required, string, `1`) ... Identifier of the News Item you want to retrieve.

+ Response 200 (application/json)

        {
            "_links": {
                "parent": {"href": "/", "title": "home"},
                "collection": {"href": "items", "title": "items"},
                "self": {"href": "items/tag:example.com,0000:newsml_BRE9A605", "title": "Item"}
            },
            "uri" : "http://site.com/items/tag:example.com,0000:newsml_BRE9A605",
            "type" : "picture",
            "versioncreated" : "2015-01-11T12:42:00Z",
            "byline" : "John Doe",
            "headline" : "Today's Picture", 
            "description_text": "Lorem ipsum",
            "description_xhtml": "<p>Lorem ipsum</p>",
            "renditions" : {
                "main" : {
                    "href" : "http://site.com/55f74d51cf0d605d5ce97a87.jpg",
                    "mimetype": "image/jpg",
                    "title" : "Large",
                    "height" : 256,
                    "width" : 512
                },
                "small" : {
                    "href" : "http://site.com/55f74d51cf0d605d5ce97a88.jpg",
                    "mimetype": "image/jpg",
                    "title" : "Thumbnail",
                    "height" : 32,
                    "width" : 32
                }
            }
        }


## News Item Collection [/items?q={q}&start_date={start_date}&end_date={end_date}&include_fields={include_fields}&exclude_fields={exclude_fields}]

### List News Items [GET]

This method is used to retrieve a list of News Items.

+ The method will return a maximum of 200 items.
+ The items retrieved by this method will be sorted in reverse chronological
  order (i.e., newest items first).


+ Parameters
    + q (optional, object) ... Search query.
    + start_date (optional, date) ... The start of the date range for the news
      items to be retrieved. If no start date is specified, the news items
      returned will be limited to the last 24 hours.
    + end_date (optional, date) ... The end of the date range for the news items
      to be retrieved. If no end date is specified, the assumed end date will be
      the current time.
    + include_fields (optional, list) ... The list of fields associated with content to
      be retrieved. Default value: All available fields will be retrieved.
    + exclude_fields (optional, list) ... The list of fields associated with content which
      should not be retrieved. Can not be used together with include_fields.

+ Response 200 (application/json)

        {
            "_meta": {
                "page": 4, "total": 4, "max_results": 25
            },
            "_links": {
                "self": {"title": "items", "href": "items?start_date=2014-01-01"},
                "parent": {"title": "home", "href": "/"}
            },
            "_items": [
                {
                    "_links": {
                        "parent": {"href": "/", "title": "home"},
                        "collection": {"href": "items", "title": "items"},
                        "self": {"href": "items/tag:example.com,0000:newsml_BRE9A605", "title": "Item"}
                    },
                    "uri": "http://site.com/items/tag:example.com,0000:newsml_BRE9A605",
                    "type": "text",
                    "version": 1,
                    "versioncreated": "2014-12-11T14:01:27+0000"
                    "headline": "Why failure isn't a dirty word",
                    "body_html": "<p>When JK Rowling delivered the 2008 Harvard commencement speech about failure, her audience consisted of hundreds of students, their families and the university’s faculty. But the impact of her words that day have since reached far wider.</p>",
                    "description_text": "text item"
                }, {
                    "_links": {
                        "parent": {"href": "/", "title": "home"},
                        "collection": {"href": "items", "title": "items"},
                        "self": {"href": "items/tag:example.com,0000:newsml_BRE9A606", "title": "Item"}
                    },
                    "uri": "http://site.com/items/tag:example.com,0000:newsml_BRE9A606",
                    "type": "picture",
                    "version": 1,
                    "versioncreated": "2014-12-11T14:01:27+0000"
                    "mimetype": "image/jpeg",
                    "description_text": "picture item - also applicable to audio/video",
                    "renditions": {
                        "original": {
                            "href": "http://farm4.staticflickr.com/3665/9203816834_9f62964627_o_d.jpg",
                            "mimetype": "image/jpeg",
                            "width": 5198,
                            "height": 3462
                        }
                    }
                }, {
                    "_links": {
                        "parent": {"href": "/", "title": "home"},
                        "collection": {"href": "items", "title": "items"},
                        "self": {"href": "items/tag:example.com,0000:newsml_BRE9A607", "title": "Item"}
                    },
                    "uri": "http://site.com/items/tag:example.com,0000:newsml_BRE9A607",
                    "type": "text",
                    "version": 1,
                    "versioncreated": "2014-12-11T14:01:27+0000"
                    "headline": "The fat-burning and energy-producing gyms",
                    "body_html": "<p>Professor Mawby feels that experiments like that at Cadbury House have a primary benefit is that they are making people aware. Through active engagement members are forced to acknowledge the physical value of energy and the cost of expanse of its wastage. </p>",
                    "description_text": "text item"
                }, {
                    "_links": {
                        "parent": {"href": "/", "title": "home"},
                        "collection": {"href": "items", "title": "items"},
                        "self": {"href": "items/tag:example.com,0000:newsml_BRE9A608", "title": "Item"}
                    },
                    "uri": "http://site.com/items/tag:example.com,0000:newsml_BRE9A608",
                    "type": "text",
                    "version": 1,
                    "versioncreated": "2014-12-11T14:01:27+0000"
                    "headline": "The best pranks in children's books",
                    "body_html": "<p><strong>Mac:</strong> OK, fifth! Thanks, Henry. It’s exciting to be sharing these recommendations in The Guardian, with our UK readers. When I lived in London, I read The Guardian every day. Also, like some rappers, I demand to be paid only in British pounds. </p>",
                    "description_text": "text item"
                }
            ]
        }


# Group Content Packages

Package Items contain grouped references to multiple News Items.

## Package [/packages/{_id}]

### Fetch a single Package Item [GET]

The item method is used to retrieve a particular NewsML-G2 Package Item in
its ninjs (News in JSON) representation.

+ Parameters
    - _id (string, `1`) ... Package Identifier.

+ Response 200 (application/json)

        {
            "_links": {
                "collection": {"href": "packages", "title": "packages"},
                "parent": {"href": "/", "title": "home"},
                "self": {
                    "href": "packages/urn:newsml:localhost:2014-12-11T15:20:18.510755:65b31275-0513-4ee5-9879-1ef9fae5fa33",
                    "title": "Package"
                }
            },
            "uri" : "http://site.com/packages/urn:newsml:localhost:2014-12-11T15:20:18.510755:65b31275-0513-4ee5-9879-1ef9fae5fa33",
            "language": "en",
            "pubstatus": "usable",
            "type": "composite",
            "version": 1,
            "versioncreated": "2014-12-11T14:01:27+0000"
            "slugline": "MARKETS-HONGKONG-STOCKS/CLOSE (URGENT)",
            "headline": "Hong Kong shares end lower on profit-taking, China slump",
            "description_text": "MARKETS-HONGKONG-STOCKS/CLOSE (URGENT):Hong Kong shares end lower on profit-taking, China slump",
            "associations": {
                "main": {
                    "uri" : "http://site.com/items/tag:reuters.com,0000:newsml_ZZN2NBZ00",
                    "type": "text",
                    "versioncreated": "2015-07-18T16:34:00Z",
                    "version": 1,
                    "located": "Hong Kong, China",
                    "slugline": "MARKETS-HONGKONG-STOCKS/CLOSE (URGENT)",
                    "headline": "Hong Kong shares end lower on profit-taking, China slump",
                    "body_html": "<p>Lorem ipsum</p>"
                },
                "picture": {
                    "uri" : "http://site.com/items/tag:example.com,0000:newsml_BRE9A607",
                    "type" : "picture",
                    "versioncreated" : "2015-07-18T16:34:00Z",
                    "copyrightnotice" : "Copyright 2015 News Agency, site.com - all rights reserved.",
                    "place" : [
                        {"name" : "Paris", "rel" : "mentions"},
                        {"name" : "France", "rel" : "mentions", "code" : "fr"}
                    ],
                    "organisation" : [{
                        "name" : "Organisation",
                        "rel" : "mentions"
                    }],
                    "byline" : "John Doe",
                    "headline" : "Lorem Ipsum",
                    "description_text": "Lorem ipsum",
                    "description_xhtml": "<p>Lorem ipsum</p>",
                    "renditions" : {
                        "large" : {
                            "href" : "http://site.com/large-picture.jpg",
                            "mimetype": "image/jpg",
                            "title" : "Large Picture",
                            "height" : 256,
                            "width" : 512
                        },
                        "thumbnail" : {
                            "href" : "http://site.com/thumbnail-picture.jpg",
                            "mimetype": "image/jpg",
                            "title" : "Thumbnail Picture",
                            "height" : 32,
                            "width" : 64
                        }
                    }
                }
            }
        }

## Package Collection [/packages?q={q}&start_date={start_date}&end_date={end_date}&include_fields={include_fields}&exclude_fields={exclude_fields}]

### List Package Items [GET]

The packages method is used to obtain a list of package items.

+ Parameters
    + q (optional, object) ... Search query.
    + start_date (optional, date) ... The start of the date range for the news
      items to be retrieved. If no start date is specified, the news items
      returned will be limited to the last 24 hours.
    + end_date (optional, date) ... The end of the date range for the news items
      to be retrieved. If no end date is specified, the assumed end date will be
      the current time.
    + include_fields (optional, list) ... The list of fields associated with content to
      be retrieved. Default value: All available fields will be retrieved.
    + exclude_fields (optional, list) ... The list of fields associated with content which
      should not be retrieved. Can not be used together with include_fields.

+ Response 200 (application/json)

        {
            "_meta": {
                "page": 1, "total": 1, "max_results": 25
            },
            "_links": {
                "self": {"title": "packages", "href": "packages?start_date=2014-01-01"},
                "parent": {"title": "home", "href": "/"}
            },
            "_items": [
                {
                    "_links": {
                        "collection": {"href": "packages", "title": "packages"},
                        "parent": {"href": "/", "title": "home"},
                        "self": {
                            "href": "packages/urn:newsml:localhost:2014-12-11T15:20:18.510755:65b31275-0513-4ee5-9879-1ef9fae5fa33",
                            "title": "Package"
                        }
                    },
                    "uri" : "http://site.com/packages/urn:newsml:localhost:2014-12-11T15:20:18.510755:65b31275-0513-4ee5-9879-1ef9fae5fa33",
                    "language": "en",
                    "pubstatus": "usable",
                    "type": "composite",
                    "version": 1,
                    "versioncreated": "2014-12-11T14:01:27+0000"
                    "slugline": "MARKETS-HONGKONG-STOCKS/CLOSE (URGENT)",
                    "headline": "Hong Kong shares end lower on profit-taking, China slump",
                    "description_text": "MARKETS-HONGKONG-STOCKS/CLOSE (URGENT):Hong Kong shares end lower on profit-taking, China slump",
                    "associations": {
                        "main": {
                            "uri" : "http://site.com/items/tag:reuters.com,0000:newsml_ZZN2NBZ00",
                            "type": "text",
                            "versioncreated": "2015-07-18T16:34:00Z",
                            "version": 1,
                            "located": "Hong Kong, China",
                            "slugline": "MARKETS-HONGKONG-STOCKS/CLOSE (URGENT)",
                            "headline": "Hong Kong shares end lower on profit-taking, China slump",
                            "body_html": "<p>Lorem ipsum</p>"
                        },
                        "picture": {
                            "uri" : "http://site.com/items/tag:example.com,0000:newsml_BRE9A607",
                            "type" : "picture",
                            "versioncreated" : "2015-07-18T16:34:00Z",
                            "copyrightnotice" : "Copyright 2015 News Agency, site.com - all rights reserved.",
                            "place" : [
                                {"name" : "Paris", "rel" : "mentions"},
                                {"name" : "France", "rel" : "mentions", "code" : "fr"}
                            ],
                            "organisation" : [{
                                "name" : "Organisation",
                                "rel" : "mentions"
                            }],
                            "byline" : "John Doe",
                            "headline" : "Lorem Ipsum",
                            "description_text": "Lorem ipsum",
                            "description_xhtml": "<p>Lorem ipsum</p>",
                            "renditions" : {
                                "large" : {
                                    "href" : "http://site.com/large-picture.jpg",
                                    "mimetype": "image/jpg",
                                    "title" : "Large Picture",
                                    "height" : 256,
                                    "width" : 512
                                },
                                "thumbnail" : {
                                    "href" : "http://site.com/thumbnail-picture.jpg",
                                    "mimetype": "image/jpg",
                                    "title" : "Thumbnail Picture",
                                    "height" : 32,
                                    "width" : 64
                                }
                            }
                        }
                    }
                }
            ]
        }
